### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by aberrio9** [VolVox99/Zillow-Scraper#1]
Hi,

Are you still supporting this scrip?

I am getting the follow error, I cloned all the file from gibhub.

Regards
.
.
PS C:\Users\aberrio\Documents\streamlit\Zillow-Scraper> python main.py https://www.zillow.com/vvvvv-county-vv/
Error getting version of chromedriver 115. Retrying with chromedriver 114 (attempt 1/5)
Traceback (most recent call last):
  File "C:\Users\xxxxxx\Documents\streamlit\Zillow-Scraper\main.py", line 161, in <module>
    main(args.URL, args.ownr)
  File "C:\Users\xxxxxx\Documents\streamlit\Zillow-Scraper\main.py", line 67, in main
    regional_map_bounds, region = get_query_data(sesh, url) if url else (default_map_bounds, None)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\Documents\streamlit\Zillow-Scraper\get_query_state.py", line 9, in get_query_data
    start = text_content.index('queryState')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: substring not found
PS C:\Users\xxxxx\Documents\streamlit\Zillow-Scraper> python main.py https://www.zillow.com/tulsa-county-ok/
Traceback (most recent call last):
  File "C:\Users\xxxxx\Documents\streamlit\Zillow-Scraper\main.py", line 161, in <module>
    main(args.URL, args.ownr)
  File "C:\Users\xxxxx\Documents\streamlit\Zillow-Scraper\main.py", line 67, in main
    regional_map_bounds, region = get_query_data(sesh, url) if url else (default_map_bounds, None)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxx\Documents\streamlit\Zillow-Scraper\get_query_state.py", line 9, in get_query_data
    start = text_content.index('queryState')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: substring not found

**Comment by VolVox99** [comment]
Hi,

I haven't updated recently, and I'm sure Zillow has changed some stuff on
their end so the code would need to be redone to still work. However, I'm
available for hire if you need a custom and updated solution.
